### ISSUE TITLE
Accepting new tasks?

### ISSUE THREAD

**Issue by miguelsalva** [ad-si/RosettaGit#11]
Hi Adrian,
Great initiative. Are you accepting new tasks to be added? First thing that comes into my mind is the fibonacci sequence, but I haven't see any CONTRIBUTING info ;)

**Comment by ad-si** [comment]
> Great initiative. 

Hi, thanks 😊. 

> Are you accepting new tasks to be added? 

Of course! I'd be very happy about any contributions!

> First thing that comes into my mind is the fibonacci sequence, but I haven't see any CONTRIBUTING info ;)

There is already a draft for it at https://rosettagit.org/drafts/fibonacci-sequence/.
Simply follow the guide at https://github.com/ad-si/RosettaGit/blob/master/contributing.md
to enable it (Good idea to add a contributing guide!)

Let me know if you need help with anything else! ☺️

**Comment by miguelsalva** [comment]
Thanks Adrian! I didn't see the draft!
Keep rockin with the project!
