### ISSUE TITLE
Links mixed up for C, C++, C# (and more?)

### ISSUE THREAD

**Issue by fingolfin** [ad-si/RosettaGit#20]
On <https://rosettagit.org/languages/> there are three entries named `C#`; they all link to <https://rosettagit.org/languages/c/>; but that page actually seems to be for C++.

**Comment by ad-si** [comment]
Thanks for the heads up! 56a678f should have mostly fixed it. There are still some places where the links aren't entirely correct, but this is going to be complicated to fix.
Does it otherwise work for you now?
