### ISSUE TITLE
ABC C++ Error

### ISSUE THREAD

**Issue by ColeyG** [ad-si/RosettaGit#26]
Hey folks!

I was using Rosetta Git to learn some C++ stuff and I found the following in the ABC C++ example:

```cpp
#include <iostream

#include <vector>
#include <string>
#include <set>
#include <cctype>


typedef std::pair<char,char> item_t;
typedef std::vector<item_t> list_t;
```

The iostream include should be closed and there shouldn't be an empty line.

**Comment by ad-si** [comment]
Thanks for the heads up! This was fixed in 36b23b8. 😊
